---
- name: Add Docker Repo Key
  apt_key:
    keyserver: p80.pool.sks-keyservers.net
    id: '{{ docker_repo_key_id }}'

- name: Add Docker Repo
  apt_repository:
    state: present
    repo: '{{ docker_repo }}'

- name: Install Docker
  apt:
    state: present
    name: '{{ docker_pkg }}'

- name: Upgrade pip, needed for docker-compse pip (https://github.com/docker/compose/issues/4102)
  shell: /usr/bin/pip install -U pip

- name: Install docker pips
  pip:
    name: '{{ item }}'
    state: latest
  with_items:
    - docker-py
    - docker-compose
